grafana/grafana-ansible-collection

- plugins/modules/alert_contact_point.py
- plugins/modules/alert_notification_policy.py
- plugins/modules/cloud_api_key.py
- plugins/modules/cloud_plugin.py
- plugins/modules/cloud_stack.py
- plugins/modules/dashboard.py
- plugins/modules/datasource.py
- plugins/modules/folder.py
Using module.fail_json(msg=missing_required_lib('requests')) format as recommended by the Ansible Community. To be merged when releasing `1.0.4`
> Using `module.fail_json(msg=missing_required_lib('requests'))` format

- roles/grafana_agent/tasks/install/directories.yaml
- roles/grafana_agent/templates/grafana-agent.service.j2
systemd ReadWritePaths is added in order to allow writing data with ProtectSystem=strict or full . https://www.freedesktop.org/software/systemd/man/systemd.exec.html#Sandboxing
Also changed WorkingDirectory to {{ grafana_agent_data_dir }}. In this case, if wal_directory is undefined in the config, then it would work with agent's default value of "", see https://github.com/grafana/agent/issues/2217
> Add ReadWritePaths

- roles/grafana_agent/README.md
- roles/grafana_agent/defaults/main.yaml
- roles/grafana_agent/tasks/install/user-group.yaml
This pull request adds a variable for adding the grafana agent user to additional groups. Fixes #40
> Configurable agent user groups (#40)

- roles/grafana_agent/tasks/configure.yaml
- roles/grafana_agent/tasks/install/user-group.yaml
- roles/grafana_agent/tasks/preflight/download.yaml
Fixes #43 .
As this check is done in ansible user module already, so it is safe to run it anytime due to module's idempotency: 
https://docs.ansible.com/ansible/latest/reference_appendices/glossary.html#term-Idempotency .
> Remove explicit user creation check

- roles/grafana_agent/tasks/main.yaml
- roles/grafana_agent/tasks/preflight.yaml
This MR removes the custom version check in favor of ansible native idempotency feature
Resolves #50
> Remove agent installation custom check

- roles/grafana_agent/tasks/preflight/download.yaml
No need to use shell/curl when fetching latest version from the api.
fixes: #53
> fix: avoid using shell for fetching latest version

- roles/grafana_agent/tasks/install/download-install.yaml
This fixes #38 by adding the CPU architecture and Grafana Agent version to the downloaded ZIP file
> Add Grafana Agent Version and CPU Arch to Downloaded ZIP

- roles/grafana_agent/README.md
- roles/grafana_agent/defaults/main.yaml
- roles/grafana_agent/tasks/preflight/download.yaml
- roles/grafana_agent/vars/main.yaml
Move _grafana_agent_base_download_url from vars to defaults to allow overriding.
This can be useful to download agent from local mirror, reusing arch detection logic of this role.
> Move _grafana_agent_base_download_url from /vars to /defaults

- roles/grafana/tasks/dashboards.yml
This should resolve the problem to import custom Grafana dashboards, when using only `grafana_dashboards_dir` without using `grafana_dashboards`
- Fixes #85
> Fix Grafana Dashboard Import

- roles/grafana_agent/handlers/main.yaml
- roles/grafana_agent/tasks/configure.yaml
- roles/grafana_agent/tasks/ga-started.yaml
- roles/grafana_agent/tasks/main.yaml
- roles/grafana_agent/vars/main.yaml
Remove forced stop
Add handler
> Make grafana_agent Idempotent

- roles/grafana/tasks/dashboards.yml
Another small fix. When you run the role in check mode the directory also needs to be created. Otherwise the run will fail.
> Create local dashboard directory in check mode

- roles/grafana_agent/vars/main.yaml
This ansible fact can be 'Darwin', 'FreeBSD' or 'Linux'. Otherwise, download link can be broken for custom os-families if 'ansible_os_family' is used.
https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_vars_facts.html
> Use 'ansible_system' env variable to detect os type

- roles/grafana/defaults/main.yml
- roles/grafana/tasks/main.yml
- roles/grafana/tasks/notifications.yml
Allow provisioning of alert resources within Grafana
> Allow alert resource provisioning

- roles/grafana/tasks/dashboards.yml
it looks like checkmode is not working for the "Create local grafana dashboard directory" task.
See https://github.com/grafana/grafana-ansible-collection/issues/107
> remove check_mode from create local directory task

- roles/grafana/tasks/configure.yml
With this Commit, the missing directory /etc/grafana/provisioning/notification for the "Create/Delete/Update alert notifications channels (provisioning)" tasks will be created.
See https://github.com/grafana/grafana-ansible-collection/issues/112
> Create missing notification directory

- roles/grafana_agent/README.md
- roles/grafana_agent/tasks/preflight/download.yaml
Curl is required on localhost, not target host. This check could fail the playbook, if curl is missing on remote host (where it is actually not needed). 
Decided not to reimplement this check on ansible controller, as it may be not that easy (if you run ansible controller on MacOS or in containers).
> Drop curl check

- roles/grafana_agent/tasks/ga-started.yaml
- roles/grafana_agent/tasks/install/download-install.yaml
This should make the grafana-agent role work in ansible's `--check` mode. I tested this against my homelab ansible playbook, and it works when there's no changes, and when the config changes. I did not test if it'll work for a fresh install because I tested installing the agent by itself before starting on this PR.
Fixes #123
> grafana-agent: Fix check mode

- roles/grafana_agent/handlers/main.yaml
systemd module is better to use as service module is targeted to restart SysV services. And here we use systemd service.
> Change handler to systemd

- roles/loki/tasks/uninstall.yml
- roles/mimir/tasks/uninstall.yml
I'd like to address the issue in the Loki and Mimir roles where the uninstall process lacks the purge option.
This is necessary for proper cleanup, especially on Debian/Ubuntu systems. This issue doesn't affect RedHat systems as they use RPM.
For illustration, you can execute `dpkg -l | grep loki` or `dpkg -l | grep mimir` after performing the uninstallation.
In the scenario, if you deploy, remove, and then redeploy, it would fail because the postinst script isn't executed during deployment.
Background info:
To ensure this problem is avoided, you can easily verify that user creation is done in `postinst` of deb package.
1. Download the Loki Deb package.
2. Extract it using `ar -x <package>.deb`.
3. Extract the control file.
4. Open the `postinst` file, where you'll find the …
> fix: Uninstall Loki and Mimir 

- roles/loki/vars/Debian.yml
- roles/promtail/vars/Debian.yml
Hi, I've used the collection to install promtail on a couple of Arm64 vms and I found that the machine architecture for the promtail installation is not mapped to arm64, to permit matching on the file to download.
The role tried to download the file with suffix `aarch64` but the correct one is `arm64`, so I committed the updated promtail architecture map, also including 2 variations for old Raspberrys
```yaml
__promtail_arch_map:
x86_64: amd64
armv6l: arm
armv7l: arm
aarch64: arm64
```
> fix: Updated promtail arch map for aarch64 matching

- roles/promtail/README.md
- roles/promtail/defaults/main.yml
- roles/promtail/tasks/deploy.yml
- roles/promtail/templates/promtail.service.j2
Currently, there is no way to set any additional Promtail arguments/flags, such as `-server.enable-runtime-reload` and `-config.expand-env=true`, outside of those configured as role variables.
Adds the ability to pass additional arguments/flags to each call of the Promtail binary.
> promtail: add support for extra args

- roles/loki/templates/config.yml.j2
This change fixes the wrong variable name being used in `roles/loki/templates/config.yml.j2`
The `roles/loki/defaults/main.yml` of the Loki role has the `loki_operational_config` commented variable, so I assume it is a typo
> Fix loki_operational_config section not getting rendered in config.yml

- roles/alloy/templates/alloy.j2
Env file variable options such as `--stability.level public-preview` in Ansible configurations cause them to be embedded without being escaped in double quotes in the env file.
For context, I have an ansible task that looks like so:
```yaml
- name: Configure Alloy
ansible.builtin.include_role:
name: grafana.grafana.alloy
vars:
alloy_config: "{{ lookup('file', '../../Home-Compose/alloy/config.alloy') }}"
alloy_env_file_vars:
CUSTOM_ARGS: "--stability.level public-preview"
```
This causes upgrade failures like it did for me today whereby the `prerm` script for the alloy package attempts executing the unescaped half, causing dpkg to spit out the error `/var/lib/dpkg/info/alloy.prerm: 6: /etc/default/alloy: public-preview: not found` for a configuration like so
``` …
```
> Update alloy.j2 to correctly embed env file variable options

- roles/grafana/tasks/main.yml
This PR fixes #357.
As @rthomson mentioned, there is no need to use privileged mode for this task, so setting `become: false` should be a simple fix for the error:
```
TASK [grafana.grafana.grafana : Find dashboards to be provisioned] *****************************************************************************************
fatal: [<REDCATED> -> localhost]: FAILED! => changed=false
module_stderr: |-
sudo: a password is required
module_stdout: ''
msg: |-
MODULE FAILURE
See stdout/stderr for the exact error
rc: 1
```
This code was added a month ago in https://github.com/grafana/grafana-ansible-collection/pull/326.
> Use become false in find task

- roles/alloy/tasks/setup-RedHat.yml
- roles/alloy/tasks/uninstall.yml
I'm installing alloy on several versions of RedHat-based operating systems and the most reliable way to support yum/dnf on 6/7/8/9 is with the `ansible.builtin.package` module instead of `ansible.builtin.dnf`.
> Alloy - Migrate RedHat install to ansible.builtin.package
